// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Opens a PDF file, creates a render session, and returns basic document metadata. */
	pdfOpen: (filePath: string) => typedError<PdfMetadata, AppError>(__TAURI_INVOKE("pdf_open", { filePath })),
	/**  Closes a PDF session and releases resources, including its cache entries. */
	pdfClose: (sessionId: string) => typedError<null, AppError>(__TAURI_INVOKE("pdf_close", { sessionId })),
	/**  Returns page dimensions for layout calculation. */
	pdfGetPageDimensions: (sessionId: string, pageIndex: number) => typedError<PageDimensions, AppError>(__TAURI_INVOKE("pdf_get_page_dimensions", { sessionId, pageIndex })),
	/**  Returns the document's outline (bookmark tree), if any. */
	pdfGetOutline: (sessionId: string) => typedError<PdfOutlineNode[], AppError>(__TAURI_INVOKE("pdf_get_outline", { sessionId })),
	/**  Returns case-insensitive text-search hits across all pages. */
	pdfSearch: (sessionId: string, query: string) => typedError<PdfSearchHit[], AppError>(__TAURI_INVOKE("pdf_search", { sessionId, query })),
	/**  Opens an EPUB file, creates a session, and returns session ID. */
	epubOpen: (filePath: string) => typedError<EpubMetadata, AppError>(__TAURI_INVOKE("epub_open", { filePath })),
	/**  Closes an EPUB session and releases resources. */
	epubClose: (sessionId: string) => typedError<null, AppError>(__TAURI_INVOKE("epub_close", { sessionId })),
	libraryAddFolder: (path: string) => typedError<number, AppError>(__TAURI_INVOKE("library_add_folder", { path })),
	libraryRemoveFolder: (path: string) => typedError<null, AppError>(__TAURI_INVOKE("library_remove_folder", { path })),
	libraryListFolders: () => typedError<LibraryFolder[], AppError>(__TAURI_INVOKE("library_list_folders")),
	libraryListEntries: () => typedError<LibraryEntry[], AppError>(__TAURI_INVOKE("library_list_entries")),
	libraryScanFolder: (path: string) => typedError<number, AppError>(__TAURI_INVOKE("library_scan_folder", { path })),
	paletteSearchLibrary: (query: string) => typedError<LibraryEntry[], AppError>(__TAURI_INVOKE("palette_search_library", { query })),
	configLoad: () => typedError<Config, AppError>(__TAURI_INVOKE("config_load")),
	configSave: (newConfig: Config) => typedError<null, AppError>(__TAURI_INVOKE("config_save", { newConfig })),
	/**  Pushes a tab onto the persistent closed-tab stack (pruned to 10 entries). */
	tabPushClosed: (filePath: string, format: string, viewState: string) => typedError<null, AppError>(__TAURI_INVOKE("tab_push_closed", { filePath, format, viewState })),
	/**  Pops the most recently closed tab, if any. */
	tabPopClosed: () => typedError<{
	file_path: string,
	format: string,
	view_state: string,
} | null, AppError>(__TAURI_INVOKE("tab_pop_closed")),
	/**  Replaces the persisted tab set with the given sessions (startup restore). */
	tabSaveSessions: (tabs: TabSessionRecord[]) => typedError<null, AppError>(__TAURI_INVOKE("tab_save_sessions", { tabs })),
	/**  Loads the previously persisted tab sessions. */
	tabLoadSessions: () => typedError<TabSessionRecord[], AppError>(__TAURI_INVOKE("tab_load_sessions")),
	/**
	 *  Toggles a bookmark for the given page. Returns whether the bookmark now
	 *  exists (`true` = added, `false` = removed).
	 */
	bookmarkToggle: (filePath: string, format: string, pagePosition: string) => typedError<boolean, AppError>(__TAURI_INVOKE("bookmark_toggle", { filePath, format, pagePosition })),
	/**  Lists bookmarks for a document in creation order. */
	bookmarkList: (filePath: string) => typedError<BookmarkRecord[], AppError>(__TAURI_INVOKE("bookmark_list", { filePath })),
};

/* Types */
export type AppError = { kind: "Pdf"; message: string } | { kind: "Epub"; message: string } | { kind: "Database"; message: string } | { kind: "Config"; message: string } | { kind: "Io"; message: string };

/**  A bookmark entry (page-scoped, label-less toggle). */
export type BookmarkRecord = {
	id: number,
	file_path: string,
	format: string,
	page_position: string,
	created_at: string,
};

/**  A closed-tab entry popped via `tab_pop_closed`. */
export type ClosedTabRecord = {
	file_path: string,
	format: string,
	view_state: string,
};

export type Config = {
	schema_version: number,
	ui: UiConfig,
	document: DocumentConfig,
};

export type DefaultLayout = "scroll" | "pages";

export type DocumentConfig = {
	default_layout: DefaultLayout,
	default_zoom: number | null,
	invert_colors: boolean,
};

export type EpubMetadata = {
	session_id: string,
};

export type LibraryEntry = {
	id: number,
	folder_id: number,
	path: string,
	format: string,
	title: string,
	size: number | null,
	mtime: number | null,
	status: string,
	error_message: string | null,
	thumbnail_path: string | null,
	created_at: string,
	updated_at: string,
};

export type LibraryFolder = {
	id: number,
	path: string,
	added_at: string,
	last_scanned_at: string | null,
};

export type PageDimensions = {
	width: number | null,
	height: number | null,
};

export type PdfMetadata = {
	session_id: string,
	page_count: number,
};

/**  A single outline (bookmark) entry in a PDF document. */
export type PdfOutlineNode = {
	title: string,
	page_index: number,
	children: PdfOutlineNode[],
};

/**  A single text-search hit within a PDF page. */
export type PdfSearchHit = {
	page_index: number,
	snippet: string,
};

/**  A persisted tab session loaded via `tab_load_sessions`. */
export type TabSessionRecord = {
	position_index: number,
	file_path: string,
	format: string,
	view_state: string,
};

export type Theme = "light" | "dark" | "system";

export type UiConfig = {
	theme: Theme,
	sidebar_open: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

