// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Opens a PDF file, creates a render session, and returns basic document metadata. */
	pdfOpen: (filePath: string) => typedError<PdfMetadata, AppError>(__TAURI_INVOKE("pdf_open", { filePath })),
	/**  Closes a PDF session and releases resources. */
	pdfClose: (sessionId: string) => typedError<null, AppError>(__TAURI_INVOKE("pdf_close", { sessionId })),
	/**  Returns page dimensions for layout calculation. */
	pdfGetPageDimensions: (sessionId: string, pageIndex: number) => typedError<PageDimensions, AppError>(__TAURI_INVOKE("pdf_get_page_dimensions", { sessionId, pageIndex })),
	/**  Opens an EPUB file, creates a session, and returns basic document metadata. */
	epubOpen: (filePath: string) => typedError<EpubMetadata, AppError>(__TAURI_INVOKE("epub_open", { filePath })),
	/**  Closes an EPUB session and releases resources. */
	epubClose: (sessionId: string) => typedError<null, AppError>(__TAURI_INVOKE("epub_close", { sessionId })),
	/**  Returns chapter content for display. */
	epubGetChapterContent: (sessionId: string, chapterIndex: number) => typedError<string, AppError>(__TAURI_INVOKE("epub_get_chapter_content", { sessionId, chapterIndex })),
	libraryAddFolder: (path: string) => typedError<number, AppError>(__TAURI_INVOKE("library_add_folder", { path })),
	libraryRemoveFolder: (path: string) => typedError<null, AppError>(__TAURI_INVOKE("library_remove_folder", { path })),
	libraryListFolders: () => typedError<LibraryFolder[], AppError>(__TAURI_INVOKE("library_list_folders")),
	libraryListEntries: () => typedError<LibraryEntry[], AppError>(__TAURI_INVOKE("library_list_entries")),
	libraryScanFolder: (path: string) => typedError<number, AppError>(__TAURI_INVOKE("library_scan_folder", { path })),
	configLoad: () => typedError<Config, AppError>(__TAURI_INVOKE("config_load")),
	configSave: (newConfig: Config) => typedError<null, AppError>(__TAURI_INVOKE("config_save", { newConfig })),
};

/* Types */
export type AppError = { kind: "Pdf"; message: string } | { kind: "Epub"; message: string } | { kind: "LibraryScan"; message: string } | { kind: "Database"; message: string } | { kind: "Config"; message: string } | { kind: "Io"; message: string } | { kind: "Protocol"; message: string };

export type Config = {
	schema_version: number,
	ui: UiConfig,
	document: DocumentConfig,
};

export type DefaultLayout = "scroll" | "pages";

export type DocumentConfig = {
	default_layout: DefaultLayout,
	default_zoom: number | null,
	invert_colors: boolean,
};

export type EpubMetadata = {
	session_id: string,
	title: string,
	author: string,
	chapter_count: number,
};

export type LibraryEntry = {
	id: number,
	folder_id: number,
	path: string,
	format: string,
	title: string,
	size: number | null,
	mtime: number | null,
	status: string,
	error_message: string | null,
	thumbnail_path: string | null,
	created_at: string,
	updated_at: string,
};

export type LibraryFolder = {
	id: number,
	path: string,
	added_at: string,
	last_scanned_at: string | null,
};

export type PageDimensions = {
	width: number | null,
	height: number | null,
};

export type PdfMetadata = {
	session_id: string,
	page_count: number,
};

export type Theme = "light" | "dark" | "system";

export type UiConfig = {
	theme: Theme,
	sidebar_open: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

